// Code generated by "stringer -type=PollStatus"; DO NOT EDIT.

package polling

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PollMiss-0]
	_ = x[PollHit-1]
	_ = x[PollFailed-2]
	_ = x[PollIllegal-3]
}

const _PollStatus_name = "PollMissPollHitPollFailedPollIllegal"

var _PollStatus_index = [...]uint8{0, 8, 15, 25, 36}

func (i PollStatus) String() string {
	if i < 0 || i >= PollStatus(len(_PollStatus_index)-1) {
		return "PollStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PollStatus_name[_PollStatus_index[i]:_PollStatus_index[i+1]]
}
