// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package msgdump

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

var lengthBufGMessageEnvelope = []byte{131}

func (t *GMessageEnvelope) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufGMessageEnvelope); err != nil {
		return err
	}

	// t.UnixMicroTime (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.UnixMicroTime)); err != nil {
		return err
	}

	// t.NetworkName (string) (string)
	if len(t.NetworkName) > 8192 {
		return xerrors.Errorf("Value in field t.NetworkName was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.NetworkName))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.NetworkName)); err != nil {
		return err
	}

	// t.Message (gpbft.GMessage) (struct)
	if err := t.Message.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *GMessageEnvelope) UnmarshalCBOR(r io.Reader) (err error) {
	*t = GMessageEnvelope{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.UnixMicroTime (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.UnixMicroTime = uint64(extra)

	}
	// t.NetworkName (string) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.NetworkName = string(sval)
	}
	// t.Message (gpbft.GMessage) (struct)

	{

		if err := t.Message.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("unmarshaling t.Message: %w", err)
		}

	}
	return nil
}

var lengthBufGMessageEnvelopeDeffered = []byte{131}

func (t *GMessageEnvelopeDeffered) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write(lengthBufGMessageEnvelopeDeffered); err != nil {
		return err
	}

	// t.UnixMicroTime (uint64) (uint64)

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.UnixMicroTime)); err != nil {
		return err
	}

	// t.NetworkName (string) (string)
	if len(t.NetworkName) > 8192 {
		return xerrors.Errorf("Value in field t.NetworkName was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.NetworkName))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.NetworkName)); err != nil {
		return err
	}

	// t.Message (typegen.Deferred) (struct)
	if err := t.Message.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *GMessageEnvelopeDeffered) UnmarshalCBOR(r io.Reader) (err error) {
	*t = GMessageEnvelopeDeffered{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajArray {
		return fmt.Errorf("cbor input should be of type array")
	}

	if extra != 3 {
		return fmt.Errorf("cbor input had wrong number of fields")
	}

	// t.UnixMicroTime (uint64) (uint64)

	{

		maj, extra, err = cr.ReadHeader()
		if err != nil {
			return err
		}
		if maj != cbg.MajUnsignedInt {
			return fmt.Errorf("wrong type for uint64 field")
		}
		t.UnixMicroTime = uint64(extra)

	}
	// t.NetworkName (string) (string)

	{
		sval, err := cbg.ReadStringWithMax(cr, 8192)
		if err != nil {
			return err
		}

		t.NetworkName = string(sval)
	}
	// t.Message (typegen.Deferred) (struct)

	{

		if err := t.Message.UnmarshalCBOR(cr); err != nil {
			return xerrors.Errorf("failed to read deferred field: %w", err)
		}
	}
	return nil
}
